default: &default
  adapter: postgresql
  username: postgres
  encoding: utf8
  pool: 8

development:
  <<: *default
  database: res_development

test:
  <<: *default
  database: res_test

production:
  <<: *default
  database: res_production